### ISSUE TITLE
add explicit convenience methods for the by mapping

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [mfalesni/selenium-smart-locator#1]
it would be help-full to be able to explicitly spell something like

`Locator.by_css(string)'

**Comment by mfalesni** [comment]
@RonnyPfannschmidt That functionality is already in selenium, if you use the `find_element_by_css_selector` and such.

**Comment by RonnyPfannschmidt** [comment]
that doesnt help when expressing one of those locators
